import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Hero from "./components/sections/Hero";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Deckoid Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Hero
        company="DIGITAL MARKETING COMPANY"
        title="Discover the Secrets Behind Rapid Growth"
        subtitle="Smart. Scalable. Results-Driven."
        bullets={[
          "Crafting Bold,memorable brand identities.",
          "Turning Online Presence into engagement.",
          "Boosting Visibility Through Targeted Marketing.",
        ]}
        buttonText="Get Your Growth Plan →"
        buttonLink="/contact"
        imageSrc="/img/turtplevideo.png"
        imageAlt="Animated Turtle"
        reverse={true}
      />
        
       {children}
        <Footer />
      </body>
    </html>
  );
}
